### ISSUE TITLE
出欠確認

### ISSUE THREAD

**Issue by yymm** [DevIPL/2016winter#1]
2016年1月予定でわりとギリギリまで出席受け付けてます。

(大会議室最大10名)
- [x] @yymm
- [x] @hashrock 
- [x] @sotoattanito 
- [x] @3100 
- [x] Y◯k◯taさん
- [x] @doragon 
- [x] @ym19851201 
- [x] @hiddenKi 
- [x] @kiyo-hiko

**Comment by hashrock** [comment]
:hand:

**Comment by sotoattanito** [comment]
簡単すぎて勉強にならないかもしれないけれど、可視化についてなら発表できます

**Comment by yymm** [comment]
@sotoattanito 是非に！

**Comment by 3100** [comment]
ノ

尚、Y田さんが会社として参加されるそうです。（見学者）

**Comment by yymm** [comment]
Y田さんの件、拝承

@3100さんも参加で良いですか？

**Comment by 3100** [comment]
参加します。

**Comment by doragon** [comment]
参加しまつ

**Comment by ym19851201** [comment]
参加の予定でお願いします(何作ろう)

**Comment by hiddenkinetics** [comment]
参加予定です！出し物は考えておらず

**Comment by hiddenKi** [comment]
2/1は北海道でした・・・不参加でorzorzorzorz
