### ISSUE TITLE
日程調整

### ISSUE THREAD

**Issue by yymm** [DevIPL/2016winter#2]
1月中〜末あたりを予定しています。

個人的な希望では

~~1/18(月)~~

です(特に理由はありません)

**Comment by yymm** [comment]
2/1（月）いかがでしょう（12/25までに特に意見がなければ決定します）

**Comment by hiddenkinetics** [comment]
2/1(月)は北海道にいます。2/2(火)～は出社しています！

**Comment by yymm** [comment]
2/3(水)開催で行こうと思いますー

**Comment by yymm** [comment]
2016　2/3（水）　18：00〜　＠IPL大会議室でほぼほぼ決定な流れです

**Comment by yymm** [comment]
2016 2/3(水) 18:00~で決定しますー
